server:
  port: 8080

spring:
  application:
    name: petfriendly-backend
  
  # H2 In-Memory Database for Development
  datasource:
    url: jdbc:h2:mem:petfriendly_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  # Disable Flyway and schema.sql for development with H2
  flyway:
    enabled: false
  
  sql:
    init:
      mode: never
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    com.petfriendly.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE